apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  mongo-root-username: {{ .Values.mongo.root_username }}
  mongo-root-password: {{ .Values.mongo.root_password }}
